version: '3.7'
services:

  server:
    build: .
    command: npm run start
    ports:
      - 3000:3000
    depends_on:
      - tile38

  tile38:
    image: tile38/tile38
    container_name: tile38
#    ports:
#      - 9851:9851
    restart: unless-stopped

#  tile38-viewer:
#    image: leighghunt/tile38-viewer
#    container_name: tile38-viewer
#    env_file: ./docker-environment-list
#    depends_on:
#      - tile38
#    ports:
#      - 80:80
#      - 443:443
#    restart: unless-stopped
#  tile38-worker:
#    image: leighghunt/tile38-worker
#    container_name: tile38-worker
#    env_file: ./docker-environment-list
#    depends_on:
#      - tile38
#      - tile38-viewer
#    restart: unless-stopped
